<a href="https://colab.research.google.com/github/Bani-Talebi/Electricity-Price-Forecasting/blob/master/Traning_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

In [ ]:
up=files.upload()

Saving Quant.csv to Quant.csv


In [ ]:
DF=pd.read_csv('Quant.csv',index_col=0,parse_dates=True)
DF.head()

label    q=0.05  ...     q=0.9     q=0.95
2019-01-01 00:00:00  2.881031 -3.470430  ...  9.914421  13.094358
2019-01-01 01:00:00  2.741079 -3.470430  ...  9.914421  13.094358
2019-01-01 02:00:00  2.422627 -3.489399  ...  7.857094  12.025231
2019-01-01 03:00:00  2.702404 -3.470430  ...  9.914421  13.133160
2019-01-01 04:00:00  2.498529 -3.489399  ...  7.857094  12.082005

[5 rows x 20 columns]

In [ ]:
df=DF.drop(columns='label')
df.head()

q=0.05     q=0.1  ...     q=0.9     q=0.95
2019-01-01 00:00:00 -3.470430 -2.997247  ...  9.914421  13.094358
2019-01-01 01:00:00 -3.470430 -2.997247  ...  9.914421  13.094358
2019-01-01 02:00:00 -3.489399 -2.997247  ...  7.857094  12.025231
2019-01-01 03:00:00 -3.470430 -2.997247  ...  9.914421  13.133160
2019-01-01 04:00:00 -3.489399 -2.997247  ...  7.857094  12.082005

[5 rows x 19 columns]

In [ ]:
L=len(df)
Q=np.arange(0.05,1,0.05)
l=len(Q)
n=4
z=np.zeros(n+1)
P=np.zeros([L,(len(z)-1)])
X=np.zeros([L,(len(z)-1)])
for j in range(L):
  a=df.iloc[j]
  d=a[-1]-a[0]
  b=d/n
  z=np.zeros(n+1)
  s=0
  c=a[0]+b
  z[0]=0
  i=1
  while s<n-1:
    if a[i]>c:
      z[s+1]=i
      s+=1
      c=a[i]+b
    i+=1
    if i==19:
      break
  z[-1]=18
  for i in range(len(z)-1):
    k1=int(z[i])
    k2=int(z[i+1])
    P[j,i]=Q[k2]-Q[k1]
    #X[j,i]=(a[k2]+a[k1])/2
  r=np.nanargmax(P[j,:])
  K=DF['label'].iloc[j]
  if r==0:
    X[j,:]=np.array([K,1.05*K,1.1*K,1.15*K])
  elif r==1:
    X[j,:]=np.array([0.95*K,K,1.05*K,1.1*K])
  elif r==2:
    X[j,:]=np.array([0.9*K,0.95*K,K,1.05*K])
  else:
    X[j,:]=np.array([0.85*K,0.9*K,0.95*K,K])



In [ ]:
for i in range(n):
  df['P_{}'.format(i)]=P[:,i]
for i in range(n):
  df['X_{}'.format(i)]=X[:,i]


In [ ]:
df.to_csv('PriceProbability1.csv')
files.download('PriceProbability1.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
Q=np.arange(0.05,1,0.05)
l=len(Q)
a=df.iloc[80]
n=4
d=a[-1]-a[0]
b=d/n
z=np.zeros(n+1)
s=0
c=a[0]+b
z[0]=0
i=1
print(c)
while s<n-1:
  if a[i]>c:
    z[s+1]=i
    s+=1
    c=a[i]+b
    print(c)
  i+=1
z[-1]=18
z

3.332895436474043
8.402426718359438
12.44616293551349
17.993779232583222


array([ 0.,  9., 14., 17., 18.])

In [ ]:
P=np.zeros(len(z)-1)
X=np.zeros(len(z)-1)
for i in range(len(z)-1):
  k1=int(z[i])
  k2=int(z[i+1])
  P[i]=Q[k2]-Q[k1]
  X[i]=(a[k2]+a[k1])/2
print(P)
print(X)


[0.45 0.25 0.15 0.05]
[ 2.00316531  6.55979906 11.35547531 14.52783311]
